add_newline = true

[[battery.display]]
style = "bold red"
threshold = 30

[character]
error_symbol = "[➜](bold red)"
success_symbol = "[➜](bold green)"

[cmd_duration]
min_time = 500

[directory]
truncate_to_repo = true
truncation_length = 3

[git_branch]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
