general {
    hide_cursor = true
    grace = 3
    no_fade_in = false
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/gruvbox-dark.png
    blur_passes = 4
    blur_size = 10
    brightness = 0.5
    vibrancy = 0.2
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(ffd040)
    inner_color = rgb(1d2021)
    font_color = rgb(fbf1c7)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 14
    check_color = rgb(60ff90)
    fail_color = rgb(ff5050)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I:%M %p')"
    color = rgb(ffd040)
    font_size = 72
    font_family = DankMono Nerd Font
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %B %d')"
    color = rgb(d5c4a1)
    font_size = 20
    font_family = DankMono Nerd Font
    position = 0, 65
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi, $USER
    color = rgb(60c0ff)
    font_size = 16
    font_family = DankMono Nerd Font
    position = 0, -80
    halign = center
    valign = center
}
